name: REVS
favicon: null
layout_spectrum: 0.53243
typography_spectrum: 0.84542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#25253c'
    - '#eab2ad'
    - '#39b0b5'
    - '#de215a'
    - '#40605d'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
