name: REVS
favicon: null
layout_spectrum: 0.18191594420932233
typography_spectrum: 0.29678127891384065
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8958365004509687
  lightness: 0.5523037377279252
  saturation: 0.27911616466008127
  rhythmicContrast: 0.3999078031629324
purpose: []
