name: REVS
favicon: null
layout_spectrum: 0.18191594420932233
typography_spectrum: 0.29678127891384065
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0f0e'
    - '#574839'
    - '#6c8078'
    - '#89515a'
    - '#49171d'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
