name: REVS
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9ff25'
    - '#8b960f'
    - '#ec3bfa'
    - '#ce005e'
    - '#fefefe'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
